Repository lfit/releng-reusable-workflows, pull requests merged in 2025-05, with the labels that each got.

#331 Chore: Remove tag-validate-semantic-action (moved to lfreleng-actions)"
  .github/actions/tag-validate-semantic-action/README.md
  .github/actions/tag-validate-semantic-action/action.yaml
Labels: chore

#332 Docs: Add docs for the Github reusable workflows
  .reuse/dep5
  REUSE.toml
  docs/compose-autotools-sonarcloud.rst
  docs/compose-docker-verify.rst
  docs/compose-gradle-publish.rst
  docs/compose-info-yaml-verify.rst
  docs/compose-jjb-verify.rst
  docs/compose-maven-merge.rst
  docs/compose-maven-verify.rst
  docs/compose-nodejs-sonatype-lifecycle.rst
  docs/compose-packer-verify.rst
  docs/compose-repository-linting.rst
  docs/composed-cmake-sonar-cloud.rst
  docs/composed-generic-sonar-cloud.rst
  docs/composed-gradle-nexus-iq.rst
  docs/composed-maven-nexus-iq.rst
  docs/composed-maven-sonar-cloud.rst
  docs/composed-prescan-sonar-cloud.rst
  docs/composed-tox-sonar-cloud.rst
  docs/dependency-review.rst
  docs/gerrit-ci-management-merge.rst
  docs/gerrit-ci-management-verify.rst
  docs/gerrit-compose-ci-management-verify.rst
  docs/gerrit-compose-required-info-yaml-verify.rst
  docs/gerrit-compose-required-rtdv3-merge.rst
  docs/gerrit-compose-required-rtdv3-verify.rst
  docs/gerrit-compose-required-tox-verify.rst
  docs/gerrit-composed-ci-management-verify.rst
  docs/gerrit-required-info-yaml-verify.rst
  docs/openssf-scorecard.rst
  docs/verify-github-actions.rst
  docs/verify-lint.rst
Labels: documentation

#339 Chore: Swap pinned-versions-action to lfreleng-actions
  .github/workflows/reuse-verify-github-actions.yaml
Labels: chore

#340 Chore: Remove redundant GHA pinned-versions-action
  .github/actions/pinned-versions-action/README.md
  .github/actions/pinned-versions-action/action.yaml
Labels: chore

#345 Chore: Update pre-commit hooks
  .pre-commit-config.yaml
Labels: chore

#351 Fix: Trigger maven-verify on relevant path changes
  .github/workflows/zzci-test-verify-maven.yaml
Labels: bug

#352 Docs: Fix markdownlint duplicate top level heading
  .github/actions/sonarqube-cloud-scan-action/README.md
Labels: documentation
